on:
  schedule:
    # run every Sunday at 6am
    - cron:  '0 6 * * SUN'

  # run manually from the Actions tab
  workflow_dispatch:

jobs:
  dependabot-cake:
    runs-on: ubuntu-latest # linux, because this is a docker-action
    steps:
      - name: check/update cake dependencies
        uses: augustoproiete-actions/nils-org--dependabot-cake-action@v1
